### ISSUE TITLE
Extension for RGBLink TAO 1pro?

### ISSUE THREAD

**Issue by LagaV** [marcingum/companion-module-rgblink-mini#1]
Are there currently any plans to extend this module also to TAO 1pro? Looking at the API there seem to be many similarities.

**Comment by marcingum** [comment]
So far I have not had such plans, but I may consider extending the module or making a new one.

Do you have API specification for TAO 1pro? 
I don't have TAO 1pro - would you be willing to test the module if I created / extended it?

**Comment by LagaV** [comment]
RGBLink provided the API doc to me and referenced to your efforts here. Will forward to you.

More than happy to test or even put in some functionality as API seems even for me simple enough.

**Comment by marcingum** [comment]
Module will be developed in https://github.com/bitfocus/companion-module-rgblink-tao1pro
